### ISSUE TITLE
Future doe and null dol issue

### ISSUE THREAD

**Issue by notcimiie** [cimiie/TASS-Scripts#1]
Exception calling "ParseExact" with "3" argument(s): "String was not recognized as a valid DateTime."

This error is returned if a student has a doe set to the future and null dol. Does not effect returned CSV in testing

**Comment by mitchellkellett** [comment]
Using the _past_ option for the 'currentstatus' parameter should alleviate that issue. 

_Noncurrent_ is a weird place to be, you're both not yet a student or you were a student.

Edit: After reading more about what you're trying to do on the forum. I would suggest replacing the nulls in the response with 31/12/9999. We have been exporting the same data to PowerBI and have found that we were getting issues with this so did a replace and that has solved our problem.

**Comment by notcimiie** [comment]
Thanks Mitchell, totally forgot about the past switch. Have updated the script. This has resolved this issue, I'll keep the null in mind if I use power BI in the future.

**Comment by mitchellkellett** [comment]
The past switch will only work if you have the TASS_student_lucene_reindex scheduled task to run prior to midnight. Otherwise it'll set them to past on their last day. If I'm reading [this post](https://forum.tassweb.com.au/t/leaving-students-dol/1945/8) correctly.

**Comment by notcimiie** [comment]
My schools is set to 10/11PM, probably worth adding to my post.
